apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ds19fy0e4-go
  janus-idp.io/tekton: ds19fy0e4-go
  backstage.io/kubernetes-id: ds19fy0e4-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ds19fy0e4-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
